# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

FirstLine.create(text: 'My nerves take aim but my sight is off')
FirstLine.create(text: 'And the body reverberates with cruelty')
FirstLine.create(text: 'Hedge your bets, tie your shoes and photosynthesize')
FirstLine.create(text: 'A capricious internal need severed in speech')
FirstLine.create(text: 'Thoughts and synapses mingle interlinked')
FirstLine.create(text: 'And all of the trumpeters faint breathless')
FirstLine.create(text: 'Baying for the swirling blood of epics')
FirstLine.create(text: 'Sorcery insipid with the routine of grooming')
FirstLine.create(text: 'We are always cautious to cauterize innocence')
FirstLine.create(text: 'And a pretext for my morning exercises')
FirstLine.create(text: 'Who will summon the courage to derobe health?')
FirstLine.create(text: 'A lax feeling sits atop a mustard-coloured wave')
FirstLine.create(text: 'It brings no joy to the swollen-lipped')
FirstLine.create(text: 'Airs and graces and misspelled faces')
FirstLine.create(text: 'And a cabbage-eared chastity left reeling')
FirstLine.create(text: 'Ungendered land churned up by gossips')
FirstLine.create(text: 'Corrosive to the holy and bereft of longing')
FirstLine.create(text: 'I am fastidious with the light of fools')
FirstLine.create(text: 'Forever ducking under a splendid narrative')
FirstLine.create(text: 'And lost somewhere adrift when space catches fire')

FirstLine.create(text: 'My nerves take aim but my sight is off')
FirstLine.create(text: 'And the body reverberates with cruelty')
FirstLine.create(text: 'Hedge your bets, tie your shoes and photosynthesize')
FirstLine.create(text: 'A capricious internal need severed in speech')
FirstLine.create(text: 'Thoughts and synapses mingle interlinked')
FirstLine.create(text: 'And all of the trumpeters faint breathless')
FirstLine.create(text: 'Baying for the swirling blood of epics')
FirstLine.create(text: 'Sorcery insipid with the routine of grooming')
FirstLine.create(text: 'We are always cautious to cauterize innocence')
FirstLine.create(text: 'And a pretext for my morning exercises')
FirstLine.create(text: 'Who will summon the courage to derobe health?')
FirstLine.create(text: 'A lax feeling sits atop a mustard-coloured wave')
FirstLine.create(text: 'It brings no joy to the swollen-lipped')
FirstLine.create(text: 'Airs and graces and misspelled faces')
FirstLine.create(text: 'And a cabbage-eared chastity left reeling')
FirstLine.create(text: 'Ungendered land churned up by gossips')
FirstLine.create(text: 'Corrosive to the holy and bereft of longing')
FirstLine.create(text: 'I am fastidious with the light of fools')
FirstLine.create(text: 'Forever ducking under a splendid narrative')
FirstLine.create(text: 'And lost somewhere adrift when space catches fire')

FirstLine.create(text: 'My nerves take aim but my sight is off')
FirstLine.create(text: 'And the body reverberates with cruelty')
FirstLine.create(text: 'Hedge your bets, tie your shoes and photosynthesize')
FirstLine.create(text: 'A capricious internal need severed in speech')
FirstLine.create(text: 'Thoughts and synapses mingle interlinked')
FirstLine.create(text: 'And all of the trumpeters faint breathless')
FirstLine.create(text: 'Baying for the swirling blood of epics')
FirstLine.create(text: 'Sorcery insipid with the routine of grooming')
FirstLine.create(text: 'We are always cautious to cauterize innocence')
FirstLine.create(text: 'And a pretext for my morning exercises')
FirstLine.create(text: 'Who will summon the courage to derobe health?')
FirstLine.create(text: 'A lax feeling sits atop a mustard-coloured wave')
FirstLine.create(text: 'It brings no joy to the swollen-lipped')
FirstLine.create(text: 'Airs and graces and misspelled faces')
FirstLine.create(text: 'And a cabbage-eared chastity left reeling')
FirstLine.create(text: 'Ungendered land churned up by gossips')
FirstLine.create(text: 'Corrosive to the holy and bereft of longing')
FirstLine.create(text: 'I am fastidious with the light of fools')
FirstLine.create(text: 'Forever ducking under a splendid narrative')
FirstLine.create(text: 'And lost somewhere adrift when space catches fire')

FirstLine.create(text: 'My nerves take aim but my sight is off')
FirstLine.create(text: 'And the body reverberates with cruelty')
FirstLine.create(text: 'Hedge your bets, tie your shoes and photosynthesize')
FirstLine.create(text: 'A capricious internal need severed in speech')
FirstLine.create(text: 'Thoughts and synapses mingle interlinked')
FirstLine.create(text: 'And all of the trumpeters faint breathless')
FirstLine.create(text: 'Baying for the swirling blood of epics')
FirstLine.create(text: 'Sorcery insipid with the routine of grooming')
FirstLine.create(text: 'We are always cautious to cauterize innocence')
FirstLine.create(text: 'And a pretext for my morning exercises')
FirstLine.create(text: 'Who will summon the courage to derobe health?')
FirstLine.create(text: 'A lax feeling sits atop a mustard-coloured wave')
FirstLine.create(text: 'It brings no joy to the swollen-lipped')
FirstLine.create(text: 'Airs and graces and misspelled faces')
FirstLine.create(text: 'And a cabbage-eared chastity left reeling')
FirstLine.create(text: 'Ungendered land churned up by gossips')
FirstLine.create(text: 'Corrosive to the holy and bereft of longing')
FirstLine.create(text: 'I am fastidious with the light of fools')
FirstLine.create(text: 'Forever ducking under a splendid narrative')
FirstLine.create(text: 'And lost somewhere adrift when space catches fire')

FirstLine.create(text: 'My nerves take aim but my sight is off')
FirstLine.create(text: 'And the body reverberates with cruelty')
FirstLine.create(text: 'Hedge your bets, tie your shoes and photosynthesize')
FirstLine.create(text: 'A capricious internal need severed in speech')
FirstLine.create(text: 'Thoughts and synapses mingle interlinked')
FirstLine.create(text: 'And all of the trumpeters faint breathless')
FirstLine.create(text: 'Baying for the swirling blood of epics')
FirstLine.create(text: 'Sorcery insipid with the routine of grooming')
FirstLine.create(text: 'We are always cautious to cauterize innocence')
FirstLine.create(text: 'And a pretext for my morning exercises')
FirstLine.create(text: 'Who will summon the courage to derobe health?')
FirstLine.create(text: 'A lax feeling sits atop a mustard-coloured wave')
FirstLine.create(text: 'It brings no joy to the swollen-lipped')
FirstLine.create(text: 'Airs and graces and misspelled faces')
FirstLine.create(text: 'And a cabbage-eared chastity left reeling')
FirstLine.create(text: 'Ungendered land churned up by gossips')
FirstLine.create(text: 'Corrosive to the holy and bereft of longing')
FirstLine.create(text: 'I am fastidious with the light of fools')
FirstLine.create(text: 'Forever ducking under a splendid narrative')
FirstLine.create(text: 'And lost somewhere adrift when space catches fire')
